## Numpy and Pandas

- 

In [5]:
import numpy as np
import time
from IPython.display import display, clear_output

In [6]:
cleanBoard = np.zeros((10, 10))
currentBoard = np.copy(cleanBoard)

In [7]:
class Snake():
    def __init__(self):
        self.x = 0
        self.y = 0
        self.dir = 'left'

In [8]:
while True:
    if currentBoard[0][0] == 0:
        currentBoard[0][0] = 1
    else:
        currentBoard[0][0] = 0
            
    clear_output(wait=True)
    print(currentBoard)
    time.sleep(1)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


KeyboardInterrupt: 